### ISSUE TITLE
Invalid user data

### ISSUE THREAD

**Issue by Mrfalk** [Patbox/StyledChat#10]
i get this message in console with this mod enabled on the server 

22.10 22:22:57 [Server] User Authenticator #1/INFO UUID of player Notch is 201aced7-93d8-4e63-8a6f-2d2da1a82fc8
22.10 22:22:58 [Connect] User NotchIP **.**.**.**
22.10 22:22:58 [Disconnect] User com.mojang.authlib.GameProfile@598cda3c[id=201aced7-93d8-4e63-8a6f-2d2da1a82fc8,name=Notch,properties={textures=[com.mojang.authlib.properties.Property@3bb08a87]},legacy=false] (/**.**.**.**:55680) has disconnected, reason: Invalid player data
22.10 22:22:58 [Server] Server thread/WARN handleDisconnection() called twice
22.10 22:22:58 [Multicraft] notch ran command Message of the Day

**Comment by Patbox** [comment]
My guess it's no longer an issue. Closing for now
