### ISSUE TITLE
Support for head emoji

### ISSUE THREAD

**Issue by haykam821** [Patbox/StyledChat#12]
Head emoji should be supported for compatible clients by making configuration not require a magic translation key and sending the proper packets.

In the configuration, a way to mark emoticons as head emojis should be available. This should allow specifying the emoji texture and fallback for vanilla clients.

Players are able to opt in to emoji registration by sending the `heademoji:request_emoji` packet. By doing so, the player opts in to receiving `heademoji:register_emoji` packets when a new head emoji is sent to that player. Once an emoji is registered to a specific player, it should not be sent again unless the player relogs or sends the `heademoji:request_emoji` packet again.

The `heademoji:register_emoji` packet is written like the following:

```java
PacketByteBuf buf = new PacketByteBuf(Unpooled.buffer());
buf.writeString("head");
buf.writeString(key);
buf.writeString(texture);
Packet<?> packet = ServerPlayNetworking.createS2CPacket(new Identifier("heademoji", "register_emoji"), buf);
```

A head emoji should be transformed into a `TranslatableText` that can be understood by both compatible and incompatible clients. It is in the format `new TranslatableText("%1$s%61188$s", fallback, key)`, so the value of `fallback` would be displayed by incompatible clients and `key` would be parsed into a head emoji by compatible clients.

**Comment by Zensonaton** [comment]
Have you managed to do this, @haykam821 ? :eyes:
