### ISSUE TITLE
Things like <insert> and <click> don't function

### ISSUE THREAD

**Issue by NyakoFox** [Patbox/StyledChat#15]
I'm an admin on my server (with `/op`) and have all permissions. However, I can't seem to use the `<insert>` and `<click>` tags (and possibly more) when writing in chat.
![image](https://files.catbox.moe/f96wuy.png)
`<hover:show_item:[value]>` also does not work (though I _could_ be using it wrong as I don't really know how to use it)
I'm using version 1.2.2+1.18

**Comment by Patbox** [comment]
This is intended as it could be security issue to the server (if configured inpropertly/giving access to users, could be abused to add fake links executing commands for example). For show_item, you put there slot nbt` {id:"item", Count: 1}`

**Comment by NyakoFox** [comment]
Could this be made a config option then? It's on a server where everyone is OP, so it doesn't matter too much if users can mask commands.
