### ISSUE TITLE
Gradients do not apply to displaynames

### ISSUE THREAD

**Issue by cadenkriese** [Patbox/StyledChat#17]
With config value
```json
"displayName": "<gradient:#ff5c5c:#c92c2c>${vanillaDisplayName}</gradient>"
```
I get an uncolored displayName
<img width="100" alt="mecommand" src="https://user-images.githubusercontent.com/13630061/145674234-baf9f130-28bb-4b0b-a835-0c26a348019f.png">
or the variable colored with a gradient
<img width="257" alt="test" src="https://user-images.githubusercontent.com/13630061/145674259-44cf2ea9-0f95-497f-871c-3ad4935331a0.png">
I'm not sure how to reproduce the individual cases, they've both happened at seemingly random times.

**Comment by Patbox** [comment]
Thats limitation of the parser. Because of how gradients work internally, they break up any text within them into seperate letters which breaks placeholder detection (as color codes are preparsed on load and only placeholders are modified on runtime)

**Comment by cadenkriese** [comment]
I would say that it's worth changing the parser mechanics a little bit. Maybe only compute gradients in runtime if the message contains a variable unless that makes the code too messy. Honestly, computing a gradient for every chat message doesn't sound like a huge deal, especially if they're on their own thread. I could be wrong, though.

**Comment by Patbox** [comment]
I have plans of reworking parser, but it will require way more abstraction. Also parsing is done on server thread to make sure there is no issues with placeholders
