### ISSUE TITLE
Player having OP priveledges always applies first permissionStyle rank in list, even with opLevel disabled, when EssentialCommands or Kits mods are loaded

### ISSUE THREAD

**Issue by pahanakun** [Patbox/StyledChat#18]
For some reason, whenever either of these mods are loaded alongside StyledChat, StyledChat will apply whatever PermissionStyle is first in the list.

I have a bunch of different ranks, opLevel is set to 5 for all of them (so that none of them require OP to apply to a player). Swapping another rank to the top of the configuration file under permissionStyles makes it so that one applies to any OP player instead.

Minecraft 1.18.1
fabric-loader: 0.12.12
fabric-api: 0.45.0+1.18
EssentialCommands: 0.19.0-mc1.18.1 https://github.com/John-Paul-R/Essential-Commands
Kits: 1.4.0-mc1.18 https://modrinth.com/mod/kits
StyledChat: 1.2.3+1.18

Also, for some reason, these two mods (EssentialCommands and Kits) also cause issues with CommandSpy - it has a config option to disable output to OPs in game, and when either of these mods are loaded, that option is ignored and it will always output to OPs as though it were set to true. This only applies to permission level 4. 3 or lower does not cause this to happen. This also overrides ranks with higher levels in roles, even if the top rank under permissionStyles has a lower level in Player Roles than another rank that is applied to a player, the styles from the top rank still apply.

**Comment by Patbox** [comment]
I will look into that

**Comment by braunly** [comment]
I have same error without EssentialCommands or Kits

**Comment by braunly** [comment]
@pahanakun update EssentialCommands and Kits to latest version
