### ISSUE TITLE
Escaping & color codes is broken

### ISSUE THREAD

**Issue by leo60228** [Patbox/StyledChat#22]
`\&a` is displayed as `<green>`, not `&a`.

**Comment by filips123** [comment]
The same thing happens with other (markdown) escapes. For example, `\*Test*` and `\*Test\*` are displayed as `<italic>Test</italic>`, similar with `\**`, `\||`, etc.

**Comment by Samsterious** [comment]
This bug appears to have resurfaced in 2.2.4+1.20.1, exactly as described before.
