### ISSUE TITLE
Incompatible with the Better Fabric Console

### ISSUE THREAD

**Issue by nikijaz** [Patbox/StyledChat#24]
**[Better Fabric Console](https://www.curseforge.com/minecraft/mc-mods/better-fabric-console)**
**Logs:** https://mclo.gs/Is8bvrE

**Comment by nikijaz** [comment]
**Styled Chat:** v1.3.2
**Better Fabric Console:** v1.0.5

**Comment by Patbox** [comment]
Also related SC code: https://github.com/Patbox/StyledChat/blob/1.19/src/main/java/eu/pb4/styledchat/StyledChatMod.java#L35

**Comment by dadoirie** [comment]
can't confirm that as I've got better fabric console and styled chat installed and minecraft does load - maybe another mod does conflict with styledchat - try loading only the bare minimum - like better fabric and styled chat and their dependencies and see if that crash still happens

**Comment by nikijaz** [comment]
Checked with only **Styled Chat**, **Better Fabric Console** and **Fabric API** - the problem remains. 
Also tried to reinstall the mods, maybe the files are corrupted, but it did not help.

I downloaded Styled Chat from [here](https://cdn.modrinth.com/data/doqSKB0e/versions/1.3.2+1.19/styled-chat-1.3.2%2B1.19.jar) and Better Fabric Console from [here](https://www.curseforge.com/minecraft/mc-mods/better-fabric-console/files/3838358).

**Comment by nikijaz** [comment]
[This](https://github.com/jpenilla/better-fabric-console/actions/runs/2492232745) version works great, but starting from [this](https://github.com/jpenilla/better-fabric-console/actions/runs/2523174495) server crashes.
So, i suppose that the problem is in [this commit](https://github.com/jpenilla/better-fabric-console/commit/4033ca8f23d7ce16da9359fcd352b3f9361b262d).

**Comment by nikijaz** [comment]
weird

**Comment by cadenkriese** [comment]
I've done more fiddling and found the conflicting mod on my end is [jpenilla/ModsCommand](https://github.com/jpenilla/ModsCommand), coincidentally by the same author. I might be able to tackle this issue and submit a PR, @Patbox what is the styled_chat:generic_hack registry used for? Also why is it considered hacky?

**Comment by Patbox** [comment]
It's used for formatting, as I wanted to keep valid in case of player/signature, while allowing for more formatting than new Mojang's suggested system (which didn't work 100% like I wanted it anyway), so Styled Chat technically display everything in player name and ignores real contents of message

**Comment by Patbox** [comment]
Maybe it's https://github.com/KyoriPowered/adventure-platform-fabric, as it is common dependency between both

**Comment by Patbox** [comment]
Should be fixed on latest

**Comment by jpenilla** [comment]
The actual conflict is with confabricate, it isn't properly updated for 1.19 yet and I've removed the dependency from my mods.
