### ISSUE TITLE
Crashing server with the following message

### ISSUE THREAD

**Issue by nctisz** [Patbox/StyledChat#27]
main/ERROR Failed to start the minecraft server
29.06 20:48:40 [Server] INFO java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'styledchat'!
29.06 20:48:40 [Server] INFO at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.14.8.jar:?]
29.06 20:48:40 [Server] INFO at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.8.jar:?]
29.06 20:48:40 [Server] INFO at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.14.8.jar:?]
29.06 20:48:40 [Server] INFO at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.8.jar:?]
29.06 20:48:40 [Server] INFO at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.14.8.jar:?]
29.06 20:48:40 [Server] INFO at net.minecraft.server.Main.main(Main.java:101) [server-intermediary.jar:?]
29.06 20:48:40 [Server] INFO at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.8.jar:?]
29.06 20:48:40 [Server] INFO at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.8.jar:?]
29.06 20:48:40 [Server] INFO at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.8.jar:?]
29.06 20:48:40 [Server] INFO at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.8.jar:?]
29.06 20:48:40 [Server] INFO Caused by: java.lang.IllegalStateException: Registry is already frozen (trying to add key ResourceKey[minecraft:chat_type / styled_chat:generic_hack])
29.06 20:48:40 [Server] INFO at net.minecraft.class_2370.method_40274(class_2370.java:81) ~[server-intermediary.jar:?]
29.06 20:48:40 [Server] INFO at net.minecraft.class_2370.method_31051(class_2370.java:91) ~[server-intermediary.jar:?]
29.06 20:48:40 [Server] INFO at net.minecraft.class_2370.method_10273(class_2370.java:87) ~[server-intermediary.jar:?]
29.06 20:48:40 [Server] INFO at net.fabricmc.fabric.impl.registry.sync.DynamicRegistrySync.lambda$setupSync$1(DynamicRegistrySync.java:63) ~[fabric-registry-sync-v0-0.9.17+23c4cfefa9-cb5b8f9d97efa7a7.jar:?]
29.06 20:48:40 [Server] INFO at net.minecraft.class_2370.md6d30f8$lambda$new$0$5(class_2370.java:596) ~[server-intermediary.jar:?]
29.06 20:48:40 [Server] INFO at net.minecraft.class_2370.handler$zfa000$setPost(class_2370.java:674) ~[server-intermediary.jar:?]
29.06 20:48:40 [Server] INFO at net.minecraft.class_2370.method_31051(class_2370.java:130) ~[server-intermediary.jar:?]
29.06 20:48:40 [Server] INFO at net.minecraft.class_2370.method_10273(class_2370.java:87) ~[server-intermediary.jar:?]
29.06 20:48:40 [Server] INFO at net.minecraft.class_2370.method_10272(class_2370.java:135) ~[server-intermediary.jar:?]
29.06 20:48:40 [Server] INFO at net.minecraft.class_5458.method_39203(class_5458.java:135) ~[server-intermediary.jar:?]
29.06 20:48:40 [Server] INFO at eu.pb4.styledchat.StyledChatMod.onInitialize(StyledChatMod.java:35) ~[styled-chat-1.3.2+1.19.jar:?]
29.06 20:48:40 [Server] INFO at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.8.jar:?]

**Comment by Patbox** [comment]
Should be fixed on latest
