### ISSUE TITLE
Incompatibility with ViaFabric

### ISSUE THREAD

**Issue by Soham52** [Patbox/StyledChat#28]
**Bug Description :-**

-The server kicks all player from versions lower than 1.19 when they send a chat message
-Server Log : https://pastebin.com/1e3eUAke

**Steps to Reproduce :-**

-Create a 1.19 server
-Install Styled Chat
-Install ViaFabric and ViaBackwards
-join through 1.18.2
-send a chat message

**Expected behaviour :-**

Chat message pops up in the chat and is seen by all

**Screenshots :-**

![image](https://user-images.githubusercontent.com/73898737/176838127-c05e0c89-cd13-42c6-804c-d5c1c97adffe.png)

**Comment by Patbox** [comment]
That's issue with ViaVersion, not Styled Chat
