### ISSUE TITLE
Player roles configuration

### ISSUE THREAD

**Issue by Redo11** [Patbox/StyledChat#3]
How to use permission attribute under permission style, while using player roles?

**Comment by Patbox** [comment]
You need to add some permission (`playerrole.role` for example) to `permission_keys` player roles config.
Then you just need to add style for that permission

**Comment by Redo11** [comment]
[roles copy.txt](https://github.com/Patbox/StyledChat/files/6725654/roles.copy.txt)
[styled-chat copy.txt](https://github.com/Patbox/StyledChat/files/6725655/styled-chat.copy.txt)
still not working

**Comment by Patbox** [comment]
Change
```
"overrides": {
            "permission_keys": "admin.role"
        }
``` to ```
"overrides": {
            "permission_keys": {"admin.role": true}
        }
```

**Comment by Redo11** [comment]
Yet, it still doesn't work for some reason. Also, why isn't that in either documentation? It should be mentioned, somewhere, at least once. Do you have any example configuration, that I could check out? Thanks so much.

**Comment by Redo11** [comment]
I switched to bleeding edge luck perms and it works, but I really like the way player roles work and would prefer it, for a server with a minimal configuration. It would be really great, if it worked more easily. Anyways, thanks for help. Hope the best for this project and have a nice day. :)
