### ISSUE TITLE
Breaking discord integration

### ISSUE THREAD

**Issue by waffleflopper** [Patbox/StyledChat#32]
Using the discord integration mod. After putting styled chat the discord integration mod no longer takes chat from in-game and displays it in discord.  Discord chat will display in in-game chat, but not the other way around.  

Any ideas/solutions? 

Running fabic 1.19 server, 1.3.3 styled chat, 2.4.5 discord integration

**Comment by Patbox** [comment]
This is issue with Discord Integrations mod not using fabric chat event/injecting poorly. Additionally I only support latest version

**Comment by waffleflopper** [comment]
Do you know if there's a fix/patch that can be executed to fix the issue?

**Comment by waffleflopper** [comment]
For anyone having this issue, check out BlockBot

**Comment by faeldray** [comment]
For anyone coming here in the future and BlockBot doesn't work for you, I can confirm that Simple Discord Link works with this mod, at least on 1.18.2.
