### ISSUE TITLE
Return value of getConfig is null

### ISSUE THREAD

**Issue by codingreg** [Patbox/StyledChat#36]
_java.lang.NullPointerException: Cannot read field "unknownStyleMessage" because the return value of "eu.pb4.styledplayerlist.config.ConfigManager.getConfig()" is null_

I'm being presented with that error. All messages in server chat are show as spoilers but not revealed - so not actually showing anything. What could be causing this?

**Comment by Patbox** [comment]
Could you send entire log?

**Comment by Patbox** [comment]
Sounds like issue with your discord bridge. Disable any formatting option it has
