### ISSUE TITLE
Outbound private message does not show up in chat

### ISSUE THREAD

**Issue by jabbarn** [Patbox/StyledChat#41]
Hey,

After upgrading to 2.2.1+1.20.1 of StyledChat, I noticed that the /msg command didn't show the sender's message but did show the message to the receiver.

this worked fine back in styled-chat-2.2.0+1.20.jar.

**Comment by jabbarn** [comment]
Hey @Patbox could u explain why this is completed?

With kind regards,

Jabbarn

**Comment by Patbox** [comment]
Yeah because I released it after :p
