### ISSUE TITLE
[1.18.2 Fabric] crash / Incompatibility

### ISSUE THREAD

**Issue by MSandro** [Patbox/StyledChat#42]
Fabric Loader 0.14.21
Fabric API 0.76.0
Styled Chat: 1.2.3
Modpack: Sky Fabrication 3 v0.6.3

Latest.log
https://gist.github.com/MSandro/7a746ff5664abb5458da9c385b6d4eee

**Comment by Patbox** [comment]
It's mod incompatibility with something, you need to find it yourself (also I don't support that old versions)
