### ISSUE TITLE
Add support SimpleChat (fork)

### ISSUE THREAD

**Issue by DonorKrovi** [Patbox/StyledChat#44]
A very good addition, since your mod does not have the most important thing is a global and local chat, I suggest implementing it on the side of your mod or adding support for an existing one, because it is what most servers need!

https://modrinth.com/mod/simplechatfork

**Comment by Patbox** [comment]
You can use this mod to add similar functionality with Styled Chat compatibility
https://modrinth.com/mod/advanced-chat
