### ISSUE TITLE
How to use nicknames?

### ISSUE THREAD

**Issue by teenangst** [Patbox/StyledChat#5]
I don't know what to set `"displayName"` to to allow for nicknames. The Placeholder API website is [not](https://placeholders.pb4.eu/users/default-placeholders) [working](https://placeholders.pb4.eu/users/mod-placeholders). There's also no mention in the readme.

**Comment by GlowingUmbreon** [comment]
Do you mean for custom nicknames? Like the player runs /nick {name}?

**Comment by Patbox** [comment]
Depending on your nicknaming mod, it should work by default or you need to use provided placeholder. Otherwise I can't fix that.
