### ISSUE TITLE
Not working with Minecraft to Discord

### ISSUE THREAD

**Issue by red2blue** [Patbox/StyledChat#6]
After installing, the messages are not being picked up by Fabric-Discord-Link. 

Nothing, no join,leave,achievement messages.

But I can talk in discord to Minecraft game.

[fabric, 1.17.1, latest version of style chat]

**Comment by Patbox** [comment]
It's issue with discord link mod, see https://github.com/arthurbambou/Fabric---Discord-Link/issues/158
I can't do anything about it
